project:
  type: website
  output-dir: docs

website:
  title: "Sandra Aguilera Moyano"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - about.qmd
      - href: resources.qmd
        text: Recursos

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

